#pragma once
#include "shaderlib/cshader.h"
class GWaterVolumetric_ps20b_Static_Index
{
public:
	GWaterVolumetric_ps20b_Static_Index()
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderStaticTest_GWaterVolumetric_ps20b 1


class GWaterVolumetric_ps20b_Dynamic_Index
{
public:
	GWaterVolumetric_ps20b_Dynamic_Index()
	{
	}

	int GetIndex() const
	{
		return 0;
	}
};

#define shaderDynamicTest_GWaterVolumetric_ps20b 1

